spring:
  datasource:
    url: jdbc:mysql://localhost:3306/backend_db?useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: "0000"
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:h2:tcp://localhost/~/projectbackend
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      #      hibernate.dialect: org.hibernate.dialect.H2Dialect
      hibernate.show_sql: true
      hibernate.format_sql: true
jwt:
  security:
    key: for.ek.project.securitykeyaassdd


logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.web: debug
    org.springframework: DEBUG
    Project.ProjectBackend.security: DEBUG

file:
  upload-dir: C:/Users/roman/Documents/CodingWorkspace/ProjectImageFolder/
  base-url: http://localhost:8080/images/